
import 'package:google_fonts/google_fonts.dart';
import 'package:gotixx/models/models.dart';
import 'package:gotixx/models/movie.dart';
import 'package:gotixx/shared/shared.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:gotixx/extensions/extensions.dart';
part 'selectable_box_widgets.dart';
part 'movie_card.dart';
part 'rating_stars.dart';
part 'browse_movie.dart';
part 'comingson_card.dart';
part 'promo_card.dart';
part 'credits_card.dart';
part 'date_card.dart';
part 'money_card.dart';
part 'transactions_card.dart';
